version: '3'

services:
  web:
    image: gitlab/gitlab-ee:13.10.0-ee.0
    restart: always
    container_name: gitlab-ee
    hostname: ${GITLAB_HOSTNAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`${GITLAB_HOSTNAME}`)"
      - "traefik.http.routers.gitlab.entrypoints=web"
      - "traefik.http.routers.gitlab.service=gitlab"
      - "traefik.http.middlewares.gitlab-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.gitlab-redirectscheme.redirectscheme.permanent=false"
      - "traefik.http.routers.gitlab.middlewares=gitlab-redirectscheme"

      - "traefik.http.routers.gitlab-secure.rule=Host(`${GITLAB_HOSTNAME}`)"
      - "traefik.http.routers.gitlab-secure.entrypoints=websecure"
      - "traefik.http.routers.gitlab-secure.service=gitlab"
      - "traefik.http.routers.gitlab-secure.tls=true"

      - "traefik.http.services.gitlab.loadbalancer.server.port=${GITLAB_PORT}"
      - "traefik.http.services.gitlab.loadbalancer.server.scheme=http"
      - "traefik.http.services.gitlab.loadbalancer.passhostheader=true"

      - "traefik.http.routers.registry.rule=Host(`${REGISTRY_HOSTNAME}`)"
      - "traefik.http.routers.registry.entrypoints=web,websecure"
      - "traefik.http.routers.registry.service=registry"
      - "traefik.http.routers.registry.tls=true"
      - "traefik.http.services.registry.loadbalancer.server.port=${REGISTRY_PORT}"

      - "traefik.http.routers.mattermost.rule=Host(`${MATTERMOST_HOSTNAME}`)"
      - "traefik.http.routers.mattermost.entrypoints=web"
      - "traefik.http.routers.mattermost.service=mattermost"
      - "traefik.http.middlewares.mattermost-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.mattermost-redirectscheme.redirectscheme.permanent=false"
      - "traefik.http.routers.mattermost.middlewares=mattermost-redirectscheme"

      - "traefik.http.routers.mattermost-secure.rule=Host(`${MATTERMOST_HOSTNAME}`)"
      - "traefik.http.routers.mattermost-secure.entrypoints=websecure"
      - "traefik.http.routers.mattermost-secure.service=mattermost"
      - "traefik.http.routers.mattermost-secure.tls=true"

      - "traefik.http.services.mattermost.loadbalancer.server.port=${MATTERMOST_PORT}"
      - "traefik.http.services.mattermost.loadbalancer.server.scheme=http"
      - "traefik.http.services.mattermost.loadbalancer.passhostheader=true"

    healthcheck:
      disable: true
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${GITLAB_HOSTNAME}'
        nginx['redirect_http_to_https'] = false
        nginx['listen_port'] = ${GITLAB_PORT}
        nginx['listen_https'] = false
        #nginx['proxy_set_headers'] = {
        #  'X-Forwarded-Proto' => 'https',
        #  'X-Forwarded-Ssl' => 'on'
        #}
        nginx['client_max_body_size'] = '2G'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${SMTP_ADDRESS}"
        gitlab_rails['smtp_port'] = ${SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${SMTP_USERNAME}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${SMTP_DOMAIN}"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['gitlab_email_from'] = 'gitlab-notifications@${SMTP_DOMAIN}'
        gitlab_rails['gitlab_email_display_name'] = 'Gitlab'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@${SMTP_DOMAIN}'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        unicorn['worker_timeout'] = 60
        unicorn['worker_processes'] = 2
        sidekiq['concurrency'] = 15
        postgresql['shared_buffers'] = "512MB"
        gitlab_rails['artifacts_enabled'] = true
        gitlab_rails['artifacts_path'] = "/var/opt/gitlab/gitlab-artifacts"
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['backup_keep_time'] = 172600
        gitlab_ci['backup_keep_time'] = 172600
        gitlab_rails['time_zone'] = "${TIMEZONE}"

        registry_external_url 'https://${REGISTRY_HOSTNAME}'
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['registry_issuer'] = "omnibus-gitlab-issuer"
        registry_nginx['listen_port'] = ${REGISTRY_PORT}
        registry_nginx['listen_https'] = false
        registry_nginx['redirect_http_to_https'] = false

        mattermost_external_url 'https://${MATTERMOST_HOSTNAME}'
        mattermost['enable'] = true
        mattermost['service_site_url'] = 'https://${MATTERMOST_HOSTNAME}'
        mattermost_nginx['listen_port'] = ${MATTERMOST_PORT}
        mattermost_nginx['listen_https'] = false
        mattermost_nginx['redirect_http_to_https'] = false
        #mattermost_nginx['proxy_set_headers'] = {
        #  "X-Forwarded-Proto" => "https",
        #  "X-Forwarded-Ssl" => "on",
        #}
        mattermost['service_use_ssl'] = false
        mattermost['gitlab_id'] = "${MATTERMOST_GITLAB_ID}"
        mattermost['gitlab_secret'] = "${MATTERMOST_GITLAB_SECRET}"
        mattermost['gitlab_scope'] = ""
        #
        # Need to contact Gitlab on HTTP
        # https://forum.mattermost.org/t/solved-mattermost-gitlab-token-request-failed/2628/6
        #
        mattermost['gitlab_auth_endpoint'] = "http://${GITLAB_HOSTNAME}/oauth/authorize"
        mattermost['gitlab_token_endpoint'] = "http://${GITLAB_HOSTNAME}/oauth/token"
        mattermost['gitlab_user_api_endpoint'] = "http://${GITLAB_HOSTNAME}/api/v4/user"
    ports:
      # Make sure your host 22 port is not already taken by SSH
      # We encourage you to change you host SSH port to reserve it for Gitlab
      - '2222:22'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

networks:
  default:
    external: 
      name: ${DEFAULT_NETWORK}

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
